version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14
    working_directory: ~/project

jobs:
  build:
    executor: default
    steps:
      - checkout

      - run:
          name: Install Trivy
          command: |
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install trivy

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS| docker login -u $DOCKER_USER--password-stdin

      - run:
          name: Build hotel booking image
          command: docker build -t balogsen/hotel:latest .

      - run:
          name: Scan Docker image with Trivy
          command: trivy image -f json -o trivy_report.json balogsen/hotel:latest

      - run:
          name: Convert Trivy JSON to human-readable format
          command: trivy image -f table balogsen/hotel:latest > trivy_report.txt

      - store_artifacts:
          path: trivy_report.txt
          destination: trivy-scan-results

      - run:
          name: Push hotel booking image
          command: |
            docker push balogsen/hotel:latest
            docker rmi balogsen/hotel:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
