version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14
    working_directory: ~/project

jobs:
  checkout:
    executor: default
    steps:
      - checkout

  code-scan:
    docker:
      - image: github/codeql-action/init@v3
    steps:
      - checkout
      - run:
          name: Initialize CodeQL
          command: |
            codeql database create codeql-db --language=javascript
            codeql database analyze codeql-db --format=sarif-latest --output=codeql-results.sarif

  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build hotel booking image
          command: docker build -t balogsen/hotel:v0 .

  image-scan:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Scan Docker image with Trivy
          command: trivy image --exit-code 1 --severity HIGH balogsen/hotel:v0

  push:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push hotel booking image
          command: |
            docker push balogsen/hotel:v0

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout
      - code-scan
      - build
      - image-scan
      - push
