version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14
    working_directory: ~/project

jobs:
  build:
    executor: default
    steps:
      - checkout

      - setup_remote_docker:
          version: default  # Use a supported and stable version

      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Build hotel booking image
          command: docker build -t balogsen/hotel:v1 .

      - run:
          name: Push hotel booking image
          command: |
            docker push balogsen/hotel:v1
            docker rmi balogsen/hotel:v1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
