version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14
    working_directory: ~/project

  security:
    docker:
      - image: aquasec/trivy:latest  # Use the latest Trivy Docker image
    working_directory: ~/project

jobs:
  code_security_scan:
    executor: default
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run npm audit (ignore failures)
          command: npm audit --audit-level=high || true

  build:
    executor: default
    steps:
      - checkout

      - setup_remote_docker:
          version: default  # Use a supported and stable version

      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Build hotel booking image
          command: docker build -t balogsen/hotel:v0 .

  image_security_scan:
    executor: security
    steps:
      - checkout

      - run:
          name: Scan Docker Image for Vulnerabilities
          command: |
            trivy image --severity HIGH,CRITICAL balogsen/hotel:v0 || true

      - run:
          name: Push Docker Image
          command: |
            docker push balogsen/hotel:v0

      - run:
          name: Remove Docker Image
          command: |
            docker rmi balogsen/hotel:v0

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - code_security_scan
      - build:
          requires:
            - code_security_scan
      - image_security_scan:
          requires:
            - build
