name: Hotel Pipeline

on:
  push:
    branches:
      - main

jobs:
  codeql-analysis:
    name: Build-CodeQL-and-deploy hotel
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    timeout-minutes: ${{ matrix.language == 'swift' && 120 || 360 }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript-typescript
        build-mode:
          - none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v3
#        with:
#          languages: ${{ matrix.language }}
#          build-mode: ${{ matrix.build-mode }}
#
#      - if: matrix.build-mode == 'manual'
#        name: Build Project
#        run: |
#          echo 'If manual build mode is set, replace this with your build commands.'
#          exit 1
#
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v3
#        with:
#          category: "/language:${{ matrix.language }}"
##CodeQL scanned 20 out of 20 JavaScript files in this invocation. Check the status page for overall coverage information: https://github.com/balogsun/hotel-booking/security/code-scanning/tools/CodeQL/status/
#
      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build hotel booking image
        run: |
          docker build -t balogsen/hotel:latest .

      - name: Scan Docker image with Trivy
        run: |
          trivy image -f json -o trivy_report.json balogsen/hotel:latest

      - name: Convert Trivy JSON to human-readable format
        run: |
          trivy image -f table balogsen/hotel:latest > trivy_report.txt

      - name: Save Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy_report.txt

#     - name: Push hotel booking image
#       run: |
#         docker push balogsen/hotel:latest
