name: Hotel Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: balogsun/hotel-booking

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache
          restore-keys: |
            ${{ runner.os }}-sonar-cache

      # Step 4: Set up and run SonarQube Scan
      - name: Set up and run SonarQube
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=sonarkey
            -Dsonar.organization=seunb-org
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.GITHUB_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Run SonarQube Scan
      - name: Run SonarQube Scan
        run: |
          echo "Running SonarQube Scan"
          mvn clean install sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Docker login
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Step 6: Build and push hotel booking image
      - name: Build and push hotel booking image
        run: |
          docker build -t balogsen/hotel:latest .
          docker rmi balogsen/hotel:latest

