name: Hotel Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: balogsun/hotel-booking

      # Step 2: Enable GitHub Code Scanning
      - name: Code Scanning
        uses: github/codeql-action/init@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Run GitHub Code Scanning
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          languages: java
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Record successful outcome for GitHub Actions
      - name: Record outcome
        run: echo "javascript_typescript=OK" >> $GITHUB_ENV

      # Step 5: Docker login
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Step 6: Build and push hotel booking image
      - name: Build and push hotel booking image
        run: |
          docker build -t balogsun/hotel:latest .
          docker push balogsun/hotel:latest
